window.SUPABASE_URL='https://kwfqgytgohkdsfcddjqj.supabase.co';
window.SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZnFneXRnb2hrZHNmY2RqcWoiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTczNTQwMjM5MCwiZXhwIjoyMDUxMDc4MzkwfQ.OuoQBVYi20sttzEZ_cu_A9qDGlqfrtXEwA7m3ZY2_rg';
